### ISSUE TITLE
[RFE] Prometheus dump capture

### ISSUE THREAD

**Issue by rsevilla87** [kube-burner/kube-burner#248]
**Is your feature request related to a problem? Please describe.**

Provide option to capture a prometheus dump over a given or benchmark's time range

Something like this is kind of provided by the tool [promdump](https://github.com/ihcsim/promdump), so we can inspire some of our code on this tool. Specially the mechanism it uses to load the TSDB from the prometheus pod using a embed binary.

**Comment by afcollins** [comment]
Not stale. Still an interesting feature. Although, we do get this functionality from our runs in prow.

**Comment by jtaleric** [comment]
yeah. the CI runs would capture the full duration/life of the cluster. This seemed to be more targeted, but achieving the same thing.

**Comment by vishnuchalla** [comment]
@rsevilla87 Do we still need this? I think we already have this functionality but instead of loading data into Prometheus we are currently able to load an existing metrics dump (i.e either through an existing `.tar` file or through `index` sub-command) into ES and use Grafana for visualizations. I am not sure on what extra functionality that we are trying to achieve with this in specific which is not already existing. Can you please clarify a bit on it?

**Comment by rsevilla87** [comment]
Closing this issue, I have different plans... Prometheus indexer? :)
