### ISSUE TITLE
[RFE] Parallel job execution

### ISSUE THREAD

**Issue by riuvshyn** [kube-burner/kube-burner#576]
**Is your feature request related to a problem? Please describe.**
Is there any way to set up parallel job execution? 

**Describe the solution you'd like**
I would love to be able to run some jobs in parallel to be able to generate more real world kind of load.

**Describe alternatives you've considered**
As an alternative I am running multiple instances of kube-burner which is quite complicated when it gets to measurements and report analysing.

**Comment by rsevilla87** [comment]
Interesting idea, I guess we can create something like execution groups, so we can group jobs of the same groups to be executed in parallel

**Comment by vishnuchalla** [comment]
@riuvshyn while we look at this issue, along side can you share the `config.yaml` file that you are using to run your jobs? If you don't mind.

**Comment by vishnuchalla** [comment]
@riuvshyn Based on your idea, here are some thoughts around its implementation.
* We enable multiple jobs execution in parallel, which will have their inbuilt measurements like `podlatency`, `vmlatency` and `pprof` etc specific to an individual job. And cluster prometheus metrics can be recorded between the start time and end time of all these jobs that executed in parallel as a whole. So that a user will be able to have detailed look at cluster level metrics while these jobs where executing in parallel and at the time taken for their relevant resources to come up.
* We can achieve this by introducing a new option in [Job](https://github.com/kube-burner/kube-burner/blob/main/pkg/config/types.go#L102) struct as `executionGroup` to group jobs that needs to be executed in parallel ensuring backward compatibility. But then all these jobs must have unique names, same type (.i.e one among of create, delete and patch) and would be better if they are in different namespaces.

Let us know if this plan aligns with your use case. Thank you.
cc: @rsevilla87 @shashank-boyapally

**Comment by ygalblum** [comment]
Reopening this issue as there's an open PR addressing it

**Comment by sanjay7178** [comment]
Should we consider a DAG based job execution , which could include a parallel execution as well ?

**Comment by vishnuchalla** [comment]
> Should we consider a DAG based job execution , which could include a parallel execution as well ?

@sanjay7178 Can you please elaborate on this idea? We were thinking of just having tests execute parallel through go threads.

**Comment by sanjay7178** [comment]
> > Should we consider a DAG based job execution , which could include a parallel execution as well ?
> 
> @sanjay7178 Can you please elaborate on this idea? We were thinking of just having tests execute parallel through go threads.

I'm not sure about the test talking about , but for executing the jobs parallelly , we could use like flow based job execution (Directed Acyclic Graph) , I mean a flow can have parallel execution and also includes a sequential job execution.
